# Kraken's API public and private keys.
api:
  public_key: "KRAKEN_API_PUBLIC_KEY"
  private_key: "KRAKEN_API_PRIVATE_KEY"

# DCA pairs configuration.
# pair: Name of the pair (list of available pairs: https://api.kraken.com/0/public/AssetPairs)
# delay: Delay in days between each buy limit order.
# amount: Amount of the order in quote asset.
dca_pairs:
  - pair: "XETHZEUR"
    delay: 1
    amount: 10
  - pair: "XBTUSDT"
    delay: 3
    amount: 10
  - pair: "LINKXBT"
    delay: 7
    amount: 0.001
