name: Main Unit Testing
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest==6.2.3 freezegun==1.1.0 pytz==2021.1 vcrpy==4.1.1
          pip install coveralls
      - name: Test with pytest
        run: pytest -vv --cov krakendca/
      - name: Push test coverage to coveralls
        run: coveralls --service=github
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}